name = "secret-ai"
main = "worker.js"
compatibility_date = "2026-04-03"
workers_dev = true

[vars]
GROQ_MODEL = "llama-3.3-70b-versatile"
GROQ_VISION_MODEL = "llama-3.2-11b-vision-preview"
ALLOWED_ORIGINS = "https://luisflmaximo.github.io"

